version: '3'

tasks:
  init:
    desc: Initialize OpenTofu
    cmds:
      - tofu init

  plan:
    desc: Plan OpenTofu changes
    cmds:
      - tofu plan

  apply:
    desc: Apply OpenTofu changes
    cmds:
      - tofu apply

  fmt:
    desc: Format OpenTofu code
    cmds:
      - tofu fmt -recursive

  validate:
    desc: Validate OpenTofu code
    cmds:
      - tofu validate

  pre-commit:
    desc: Run pre-commit hooks on all files
    cmds:
      - pre-commit run --all-files

  commit:
    desc: Create a new commit using commitizen
    cmds:
      - cz commit
